// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Secunitec.Billing.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class DominioBilling : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "creada_en",
                table: "billing_facturas",
                type: "timestamp with time zone",
                nullable: false,
                defaultValueSql: "now()");

            // Las facturas existentes toman la hora de la migración; las nuevas reciben siempre CreadaEn del dominio.
            migrationBuilder.Sql("ALTER TABLE billing_facturas ALTER COLUMN creada_en DROP DEFAULT;");

            migrationBuilder.AddColumn<string>(
                name: "motivo_anulacion",
                table: "billing_facturas",
                type: "character varying(250)",
                maxLength: 250,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_billing_facturas_obligado_id_creada_en",
                table: "billing_facturas",
                columns: new[] { "obligado_id", "creada_en" });

            migrationBuilder.CreateIndex(
                name: "IX_billing_facturas_obligado_id_estado",
                table: "billing_facturas",
                columns: new[] { "obligado_id", "estado" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_billing_facturas_obligado_id_creada_en",
                table: "billing_facturas");

            migrationBuilder.DropIndex(
                name: "IX_billing_facturas_obligado_id_estado",
                table: "billing_facturas");

            migrationBuilder.DropColumn(
                name: "creada_en",
                table: "billing_facturas");

            migrationBuilder.DropColumn(
                name: "motivo_anulacion",
                table: "billing_facturas");
        }
    }
}
