// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Secunitec.Billing.Infrastructure;

#nullable disable

namespace Secunitec.Billing.Infrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Secunitec.Billing.Domain.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("ObligadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligado_id");

                    b.Property<string>("Rtn")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("rtn");

                    b.HasKey("Id");

                    b.HasIndex("ObligadoId");

                    b.ToTable("billing_clientes", (string)null);
                });

            modelBuilder.Entity("Secunitec.Billing.Domain.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cai")
                        .HasMaxLength(37)
                        .HasColumnType("character varying(37)")
                        .HasColumnName("cai");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<Guid>("CreadaPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creada_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<decimal>("Isv")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("isv");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<Guid>("ObligadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligado_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "ObligadoId");

                    b.HasIndex("ObligadoId", "CreadaEn");

                    b.HasIndex("ObligadoId", "Estado");

                    b.HasIndex("ObligadoId", "Numero")
                        .IsUnique();

                    b.ToTable("billing_facturas", null, t =>
                        {
                            t.HasCheckConstraint("ck_montos", "subtotal >= 0 AND isv >= 0 AND total = subtotal + isv");
                        });
                });

            modelBuilder.Entity("Secunitec.Billing.Domain.LineaFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Exento")
                        .HasColumnType("boolean")
                        .HasColumnName("exento");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("importe");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<Guid>("factura_id")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id");

                    b.HasKey("Id");

                    b.HasIndex("factura_id");

                    b.ToTable("billing_lineas", null, t =>
                        {
                            t.HasCheckConstraint("ck_linea", "cantidad > 0 AND precio_unitario > 0 AND importe >= 0");
                        });
                });

            modelBuilder.Entity("Secunitec.Billing.Domain.ObligadoTributario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Cai")
                        .IsRequired()
                        .HasMaxLength(37)
                        .HasColumnType("character varying(37)")
                        .HasColumnName("cai");

                    b.Property<DateOnly>("FechaLimiteEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_limite_emision");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefijo");

                    b.Property<int>("RangoDesde")
                        .HasColumnType("integer")
                        .HasColumnName("rango_desde");

                    b.Property<int>("RangoHasta")
                        .HasColumnType("integer")
                        .HasColumnName("rango_hasta");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rtn")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("rtn");

                    b.Property<int>("SiguienteCorrelativo")
                        .HasColumnType("integer")
                        .HasColumnName("siguiente_correlativo");

                    b.HasKey("Id");

                    b.HasIndex("Rtn")
                        .IsUnique();

                    b.ToTable("billing_obligados", null, t =>
                        {
                            t.HasCheckConstraint("ck_rango", "rango_desde > 0 AND rango_hasta >= rango_desde AND siguiente_correlativo >= rango_desde AND siguiente_correlativo <= rango_hasta + 1");
                        });
                });

            modelBuilder.Entity("Secunitec.Billing.Domain.Cliente", b =>
                {
                    b.HasOne("Secunitec.Billing.Domain.ObligadoTributario", null)
                        .WithMany()
                        .HasForeignKey("ObligadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Secunitec.Billing.Domain.Factura", b =>
                {
                    b.HasOne("Secunitec.Billing.Domain.ObligadoTributario", null)
                        .WithMany()
                        .HasForeignKey("ObligadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Secunitec.Billing.Domain.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId", "ObligadoId")
                        .HasPrincipalKey("Id", "ObligadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Secunitec.Billing.Domain.LineaFactura", b =>
                {
                    b.HasOne("Secunitec.Billing.Domain.Factura", null)
                        .WithMany("Lineas")
                        .HasForeignKey("factura_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Secunitec.Billing.Domain.Factura", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
