using Microsoft.EntityFrameworkCore.Migrations;

namespace Secunitec.Billing.Infrastructure.Migrations;

// Migración escrita a mano en la etapa 2.2; el Designer y el snapshot se generaron después (etapa 4) sin cambiar su SQL.
// Su id tiene 12 dígitos y EF asume 14: se aplica bien con MigrateAsync, pero `dotnet ef database update` o
// `migrations remove` no la encuentran por nombre. No renombrarla: las bases existentes la tienen en su historial.
public sealed partial class InitialBilling : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE billing_obligados (
                id uuid PRIMARY KEY, rtn varchar(14) NOT NULL UNIQUE, razon_social varchar(250) NOT NULL,
                cai varchar(37) NOT NULL, prefijo varchar(10) NOT NULL,
                rango_desde integer NOT NULL, rango_hasta integer NOT NULL,
                siguiente_correlativo integer NOT NULL, fecha_limite_emision date NOT NULL, activo boolean NOT NULL,
                CONSTRAINT ck_rango CHECK (rango_desde > 0 AND rango_hasta >= rango_desde AND
                    siguiente_correlativo >= rango_desde AND siguiente_correlativo <= rango_hasta + 1)
            );
            CREATE TABLE billing_clientes (
                id uuid PRIMARY KEY, obligado_id uuid NOT NULL REFERENCES billing_obligados(id),
                nombre varchar(250) NOT NULL, rtn varchar(14), email varchar(250),
                CONSTRAINT ak_cliente_tenant UNIQUE (id, obligado_id)
            );
            CREATE TABLE billing_facturas (
                id uuid PRIMARY KEY, obligado_id uuid NOT NULL REFERENCES billing_obligados(id),
                cliente_id uuid NOT NULL, creada_por uuid NOT NULL,
                estado varchar(10) NOT NULL, numero varchar(20), cai varchar(37), fecha_emision date,
                subtotal numeric(18,2) NOT NULL, isv numeric(18,2) NOT NULL, total numeric(18,2) NOT NULL,
                CONSTRAINT fk_factura_cliente_tenant FOREIGN KEY (cliente_id, obligado_id)
                    REFERENCES billing_clientes(id, obligado_id),
                CONSTRAINT ck_montos CHECK (subtotal >= 0 AND isv >= 0 AND total = subtotal + isv),
                CONSTRAINT uq_factura_numero UNIQUE (obligado_id, numero)
            );
            CREATE INDEX ix_facturas_cliente_tenant ON billing_facturas(cliente_id, obligado_id);
            CREATE TABLE billing_lineas (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                factura_id uuid NOT NULL REFERENCES billing_facturas(id) ON DELETE CASCADE,
                descripcion varchar(250) NOT NULL, cantidad numeric(18,4) NOT NULL,
                precio_unitario numeric(18,2) NOT NULL, exento boolean NOT NULL,
                importe numeric(18,2) NOT NULL,
                CONSTRAINT ck_linea CHECK (cantidad > 0 AND precio_unitario > 0 AND importe >= 0)
            );
            CREATE INDEX ix_lineas_factura ON billing_lineas(factura_id);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE billing_lineas;
            DROP TABLE billing_facturas;
            DROP TABLE billing_clientes;
            DROP TABLE billing_obligados;
            """);
    }
}
